services:
  - type: web
    name: alliance-portal-backend
    env: node
    rootDir: alliance-portal-backend
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: LOG_LEVEL
        value: info
